export const CREATE_TASK = 'CREATE_TASK';
export const REMOVE_TASK = 'REMOVE_TASK';
export const RENAME_TASK = 'RENAME_TASK';
export const EDIT_TASK_DESCRIPTION = 'EDIT_TASK_DESCRIPTION';
export const COMPLETE_TASK = 'COMPLETE_TASK';
export const EDIT_TASK_CATEGORY = 'EDIT_TASK_CATEGORY';

export default {
  CREATE_TASK,
  REMOVE_TASK,
  RENAME_TASK,
  EDIT_TASK_DESCRIPTION,
  COMPLETE_TASK,
  EDIT_TASK_CATEGORY,
};
