export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const RENAME_CATEGORY = 'RENAME_CATEGORY';
export const ADD_CHILD_CATEGORY = 'ADD_CHILD_CATEGORY';
export const REMOVE_CHILD_CATEGORY = 'REMOVE_CHILD_CATEGORY';
export const ADD_TASK_TO_CATEGORY = 'ADD_TASK_TO_CATEGORY';
export const REMOVE_TASK_FROM_CATEGORY = 'REMOVE_TASK_FROM_CATEGORY';

export default {
  CREATE_CATEGORY,
  REMOVE_CATEGORY,
  RENAME_CATEGORY,
  ADD_CHILD_CATEGORY,
  REMOVE_CHILD_CATEGORY,
  ADD_TASK_TO_CATEGORY,
  REMOVE_TASK_FROM_CATEGORY,
};
